#!/usr/bin/env python3
import argparse
import json
import re
import sys
import urllib.parse
import urllib.request


def api_get(api_url, params):
    params = dict(params)
    params.setdefault("format", "json")
    url = api_url + "?" + urllib.parse.urlencode(params, doseq=True)
    with urllib.request.urlopen(url) as r:
        return json.loads(r.read().decode("utf-8"))


def chunks(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def get_modules(api_url, modules):
    out = []
    for chunk in chunks(modules, 50):
        data = api_get(api_url, {
            "action": "paraminfo",
            "modules": "|".join(chunk),
            "helpformat": "none",
        })
        out.extend(data.get("paraminfo", {}).get("modules", []))
    return out


def lua_string(s):
    return json.dumps(str(s))


def lua_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return lua_string(v)


def lua_set(values, indent=""):
    lines = ["{"]
    for v in sorted(str(x) for x in values):
        lines.append(f'{indent}  [{lua_string(v)}] = true,')
    lines.append(indent + "}")
    return "\n".join(lines)


def normalize_type(t):
    if isinstance(t, list):
        return {
            "kind": "enum",
            "values": [str(x) for x in t],
        }

    if not isinstance(t, str):
        return {"kind": "string"}

    t = t.lower()

    if t in ("boolean", "bool"):
        return {"kind": "boolean"}
    if t in ("integer", "int", "limit", "namespace"):
        return {"kind": "integer"}
    if t in ("timestamp",):
        return {"kind": "timestamp"}

    return {"kind": "string"}


def module_to_policy(mod):
    params = {}

    for p in mod.get("parameters", []):
        name = p.get("name")
        if not name:
            continue

        nt = normalize_type(p.get("type"))

        params[name] = {
            "required": bool(p.get("required")),
            "multi": bool(p.get("multi")),
            "type": nt["kind"],
        }

        if nt["kind"] == "enum":
            params[name]["values"] = nt["values"]

    return params


def generate_lua(policy):
    return f"""-- Generated by mw_waf_gen.py
-- Positive-security MediaWiki API validator for OpenResty.
--
-- Return values:
--   0 = allow
--   nonzero = block
--
-- Usage from access_by_lua_file:
--
--   local mw = require "mediawiki"
--   local rc, reason = mw.validate()
--   if rc ~= 0 then
--       ngx.status = 403
--       ngx.say("Blocked: " .. reason)
--       return ngx.exit(403)
--   end

local _M = {{}}

local allowed_uris = {{
    ["/api.php"] = true,
    ["/index.php"] = true,
    ["/load.php"] = true,
    ["/rest.php"] = true,
}}

local allowed_methods = {{
    GET = true,
    POST = true,
    HEAD = true,
}}

local boolean_values = {{
    [""] = true,
    ["1"] = true,
    ["0"] = true,
    ["true"] = true,
    ["false"] = true,
    ["yes"] = true,
    ["no"] = true,
}}

local global_params = {lua_policy_table(policy["global_params"])}

local action_modules = {lua_policy_table(policy["action_modules"])}

local query_submodules = {lua_policy_table(policy["query_submodules"])}

local function is_integer(v)
    return type(v) == "string" and v:match("^%-?%d+$") ~= nil
end

local function is_timestamp(v)
    return type(v) == "string" and (
        v:match("^%d%d%d%d%-%d%d%-%d%dT%d%d:%d%d:%d%dZ$") ~= nil
        or v:match("^%d%d%d%d%-%d%d%-%d%d %d%d:%d%d:%d%d$") ~= nil
        or v == "now"
    )
end

local function split_multi(v)
    local out = {{}}
    for part in tostring(v):gmatch("[^|]+") do
        out[#out + 1] = part
    end
    return out
end

local function validate_value(spec, v)
    if spec.type == "boolean" then
        return boolean_values[tostring(v)] == true
    end

    if spec.type == "integer" then
        return is_integer(tostring(v))
    end

    if spec.type == "timestamp" then
        return is_timestamp(tostring(v))
    end

    if spec.type == "enum" then
        if spec.multi then
            for _, part in ipairs(split_multi(v)) do
                if not spec.values[part] then
                    return false
                end
            end
            return true
        end

        return spec.values[tostring(v)] == true
    end

    -- Paraminfo often reports complex values as string.
    -- This intentionally allows arbitrary string content for known string params.
    return type(v) == "string"
end

local function validate_params(args, specs)
    for name, spec in pairs(specs) do
        if spec.required and args[name] == nil then
            return false, "missing required parameter: " .. name
        end
    end

    for name, value in pairs(args) do
        local spec = specs[name]

        if not spec then
            return false, "unknown parameter: " .. name
        end

        if type(value) == "table" then
            for _, item in ipairs(value) do
                if not validate_value(spec, item) then
                    return false, "invalid value for parameter: " .. name
                end
            end
        else
            if not validate_value(spec, value) then
                return false, "invalid value for parameter: " .. name
            end
        end
    end

    return true, "ok"
end

local function merge_specs(...)
    local merged = {{}}

    for i = 1, select("#", ...) do
        local src = select(i, ...)
        if src then
            for k, v in pairs(src) do
                merged[k] = v
            end
        end
    end

    return merged
end

function _M.validate()
    local uri = ngx.var.uri
    local method = ngx.req.get_method()

    if not allowed_uris[uri] then
        return 10, "unknown uri: " .. tostring(uri)
    end

    if not allowed_methods[method] then
        return 11, "method not allowed: " .. tostring(method)
    end

    if uri ~= "/api.php" then
        -- Strict URI allowlist, but non-API endpoints need separate policies.
        -- For now, allow known MediaWiki non-API endpoints through.
        return 0, "ok"
    end

    ngx.req.read_body()

    local args = ngx.req.get_uri_args()

    if method == "POST" then
        local post_args = ngx.req.get_post_args()
        for k, v in pairs(post_args) do
            args[k] = v
        end
    end

    local action = args.action or "query"

    if type(action) == "table" then
        return 20, "duplicate action parameter"
    end

    local module_specs = action_modules[action]
    if not module_specs then
        return 21, "unknown action module: " .. tostring(action)
    end

    local specs = merge_specs(global_params, module_specs)

    if action == "query" then
        for family, modules in pairs(query_submodules) do
            local selected = args[family]
            if selected then
                for _, modname in ipairs(split_multi(selected)) do
                    local sub_specs = modules[modname]
                    if not sub_specs then
                        return 22, "unknown query submodule: " .. family .. "=" .. modname
                    end
                    specs = merge_specs(specs, sub_specs)
                end
            end
        end
    end

    local ok, reason = validate_params(args, specs)
    if not ok then
        return 30, reason
    end

    return 0, "ok"
end

return _M
"""


def lua_policy_table(obj, indent=""):
    if isinstance(obj, dict):
        lines = ["{"]
        for k in sorted(obj.keys()):
            v = obj[k]
            lines.append(f"{indent}  [{lua_string(k)}] = {lua_policy_table(v, indent + '  ')},")
        lines.append(indent + "}")
        return "\n".join(lines)

    if isinstance(obj, list):
        # Lists are enum values.
        return lua_set(obj, indent)

    if isinstance(obj, bool):
        return "true" if obj else "false"

    if isinstance(obj, (int, float)):
        return str(obj)

    return lua_string(obj)


def build_policy(modules):
    action_modules = {}
    query_submodules = {}
    global_params = {}

    for key, mod in modules.items():
        name = mod.get("name")
        path = mod.get("path") or name

        params = module_to_policy(mod)

        if path == "main":
            global_params = params
            continue

        if path and path.startswith("query+"):
            parts = path.split("+", 1)
            sub = parts[1]
            group = mod.get("group") or guess_query_group(name, sub)

            query_submodules.setdefault(group, {})[name] = params
            continue

        if name:
            action_modules[name] = params

    return {
        "global_params": global_params,
        "action_modules": action_modules,
        "query_submodules": query_submodules,
    }


def guess_query_group(name, sub):
    # Common query module families.
    # MediaWiki paraminfo usually includes enough metadata, but this fallback helps.
    if name in {
        "info", "revisions", "images", "imageinfo", "links", "langlinks",
        "categories", "templates", "contributors", "extracts", "pageprops",
    }:
        return "prop"

    if name in {
        "allpages", "allimages", "allusers", "categorymembers",
        "backlinks", "embeddedin", "search", "recentchanges", "logevents",
    }:
        return "list"

    if name in {
        "siteinfo", "userinfo", "tokens", "filerepoinfo", "languageinfo",
        "notifications",
    }:
        return "meta"

    return "prop"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("base_url", help="Example: http://localhost:8889/")
    ap.add_argument("--json-output", default="mediawiki-api-paraminfo.json")
    ap.add_argument("--lua-output", default="mediawiki.lua")
    args = ap.parse_args()

    api_url = args.base_url.rstrip("/") + "/api.php"

    seeds = ["main", "*", "query+**"]

    modules = get_modules(api_url, seeds)
    names = sorted({m.get("path") or m.get("name") for m in modules if m.get("name")})
    more = get_modules(api_url, names)

    by_name = {}
    for m in modules + more:
        key = m.get("path") or m.get("name")
        if key:
            by_name[key] = m

    result = {
        "api_url": api_url,
        "module_count": len(by_name),
        "modules": dict(sorted(by_name.items())),
    }

    with open(args.json_output, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, sort_keys=True)

    policy = build_policy(by_name)
    lua = generate_lua(policy)

    with open(args.lua_output, "w", encoding="utf-8") as f:
        f.write(lua)

    print(f"Wrote {args.json_output}")
    print(f"Wrote {args.lua_output}")
    print(f"Modules found: {len(by_name)}")
    print(f"Action modules: {len(policy['action_modules'])}")
    print(f"Query families: {', '.join(sorted(policy['query_submodules']))}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


