-- Generated by gen_edit_forms.py - do not hand-edit, re-run the generator.
local T = require "waf.types"
--
-- index_post_form: the standard wikitext edit-submission form (EditPage.php),
-- from editpage-fields.json (extract_mediawiki_api.py, heuristic
-- $request->getXxx() scan - candidate field NAMES only, no type info, so most
-- fields are generously-capped nullable strings; a handful of known
-- checkbox/enum fields get a tighter override above). None are marked required
-- since MediaWiki's own form-building logic determines which fields are
-- present per action (preview/save/diff).
local index_post_form = T.object({
  bot = T.nullable(T.string({ max=8 })),
  editRevId = T.nullable(T.string({ max=512 })),
  editintro = T.nullable(T.string({ max=512 })),
  format = T.nullable(T.string({ max=512 })),
  minor = T.nullable(T.string({ max=8 })),
  mode = T.nullable(T.string({ max=512 })),
  model = T.nullable(T.string({ max=512 })),
  nosummary = T.nullable(T.string({ max=8 })),
  oldid = T.nullable(T.string({ max=512 })),
  parentRevId = T.nullable(T.string({ max=512 })),
  preload = T.nullable(T.string({ max=512 })),
  ['preloadparams[]'] = T.nullable(T.string({ max=2048 })),
  preloadtitle = T.nullable(T.string({ max=512 })),
  preview = T.nullable(T.string({ max=8 })),
  redlink = T.nullable(T.string({ max=8 })),
  section = T.nullable(T.string({ max=512 })),
  summary = T.nullable(T.string({ max=2048 })),
  undo = T.nullable(T.string({ max=512 })),
  undoafter = T.nullable(T.string({ max=512 })),
  watchthis = T.nullable(T.string({ max=8 })),
  wpAllowedProblematicRedirectTarget = T.nullable(T.string({ max=8 })),
  wpAntispam = T.nullable(T.string({ max=64 })),
  wpAutoSummary = T.nullable(T.string({ max=2048 })),
  wpChangeTags = T.nullable(T.string({ max=512 })),
  wpChangeTagsAfterPreview = T.nullable(T.string({ max=8 })),
  wpDiff = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpEdittime = T.nullable(T.string({ max=512 })),
  wpExtraQueryRedirect = T.nullable(T.string({ max=512 })),
  wpIgnoreBlankArticle = T.nullable(T.string({ max=8 })),
  wpIgnoreBlankSummary = T.nullable(T.string({ max=8 })),
  wpIgnoreProblematicRedirects = T.nullable(T.string({ max=8 })),
  wpIgnoreRevisionDeleted = T.nullable(T.string({ max=8 })),
  wpMinoredit = T.nullable(T.string({ max=8 })),
  wpPreview = T.nullable(T.string({ max=8 })),
  wpRecreate = T.nullable(T.string({ max=8 })),
  wpSave = T.nullable(T.string({ max=512 })),
  wpScrolltop = T.nullable(T.string({ max=512 })),
  wpSection = T.nullable(T.string({ max=512 })),
  wpSectionTitle = T.nullable(T.string({ max=512 })),
  wpStarttime = T.nullable(T.string({ max=512 })),
  wpSummary = T.nullable(T.string({ max=2048 })),
  wpTextbox1 = T.nullable(T.string({ max=512 })),
  wpTextbox2 = T.nullable(T.string({ max=512 })),
  wpUltimateParam = T.nullable(T.string({ max=4, enum={ ['1']=true } })),
  wpUndidRevision = T.nullable(T.string({ max=512 })),
  wpUndoAfter = T.nullable(T.string({ max=512 })),
  wpUnicodeCheck = T.nullable(T.string({ max=64 })),
  wpWatchlistExpiry = T.nullable(T.string({ max=512 })),
  wpWatchlistLabels = T.nullable(T.string({ max=512 })),
  wpWatchthis = T.nullable(T.string({ max=8 })),
})

-- action_forms: one per index.php action=X POST target
-- (includes/Actions/*.php + Page/ProtectionForm.php), from index-actions.json.
-- Candidate field NAMES only (getFormFields() types where available, else a
-- heuristic scan). title/wpEditToken/wpFormIdentifier are added to every form:
-- they're injected unconditionally by HTMLForm::getHiddenFields() for any
-- POST-method form, not read back by the action's own code, so no scan of it
-- ever finds them. Which action= a POST is for lives in the query string, not
-- the body, so mediawiki.lua's "index php post" route tries index_post_form
-- and every one of these in turn via form_schemas (core.lua: passes if any
-- one matches).
-- DeleteAction (action='delete', method=form_fields) -- includes/Actions/DeleteAction.php
local action_deleteaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpConfirmB = T.nullable(T.string({ max=512 })),
  wpConfirmationRevId = T.nullable(T.string({ max=512 })),
  wpDeleteReasonList = T.nullable(T.string({ max=1024 })),
  wpDeleteTalk = T.nullable(T.string({ max=8 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpReason = T.nullable(T.string({ max=1024 })),
  wpSuppress = T.nullable(T.string({ max=8 })),
  wpWatch = T.nullable(T.string({ max=8 })),
  wpWatchlistExpiry = T.nullable(T.string({ max=512 })),
})

-- MarkpatrolledAction (action='markpatrolled', method=heuristic) -- includes/Actions/MarkpatrolledAction.php
local action_markpatrolledaction_form = T.object({
  rcid = T.nullable(T.string({ max=512 })),
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
})

-- McrRestoreAction (action='mcrrestore', method=form_fields) -- includes/Actions/McrUndoAction.php
local action_mcrrestoreaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpSummary = T.nullable(T.string({ max=2048 })),
  wpdiff = T.nullable(T.string({ max=512 })),
  wpsummarypreview = T.nullable(T.string({ max=512 })),
})

-- McrUndoAction (action='mcrundo', method=form_fields) -- includes/Actions/McrUndoAction.php
local action_mcrundoaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpSummary = T.nullable(T.string({ max=2048 })),
  wpdiff = T.nullable(T.string({ max=512 })),
  wpsummarypreview = T.nullable(T.string({ max=512 })),
})

-- ProtectAction (action='protect', method=heuristic) -- includes/Page/ProtectionForm.php
local action_protectaction_form = T.object({
  ['mwProtect-cascade'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-create'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-edit'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-move'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-upload'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-create'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-edit'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-move'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-upload'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-reason'] = T.nullable(T.string({ max=1024 })),
  mwProtectWatch = T.nullable(T.string({ max=512 })),
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-create'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-edit'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-move'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-upload'] = T.nullable(T.string({ max=512 })),
  wpProtectReasonSelection = T.nullable(T.string({ max=1024 })),
})

-- PurgeAction (action='purge', method=form_fields) -- includes/Actions/PurgeAction.php
local action_purgeaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpintro = T.nullable(T.string({ max=512 })),
})

-- RevertAction (action='revert', method=form_fields) -- includes/Actions/RevertAction.php
local action_revertaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpcomment = T.nullable(T.string({ max=512 })),
  wpintro = T.nullable(T.string({ max=512 })),
})

-- RollbackAction (action='rollback', method=form_fields) -- includes/Actions/RollbackAction.php
local action_rollbackaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpintro = T.nullable(T.string({ max=512 })),
})

-- UnprotectAction (action='unprotect', method=heuristic) -- includes/Page/ProtectionForm.php
local action_unprotectaction_form = T.object({
  ['mwProtect-cascade'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-create'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-edit'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-move'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-expiry-upload'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-create'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-edit'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-move'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-level-upload'] = T.nullable(T.string({ max=512 })),
  ['mwProtect-reason'] = T.nullable(T.string({ max=1024 })),
  mwProtectWatch = T.nullable(T.string({ max=512 })),
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-create'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-edit'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-move'] = T.nullable(T.string({ max=512 })),
  ['wpProtectExpirySelection-upload'] = T.nullable(T.string({ max=512 })),
  wpProtectReasonSelection = T.nullable(T.string({ max=1024 })),
})

-- UnwatchAction (action='unwatch', method=form_fields) -- includes/Actions/UnwatchAction.php
local action_unwatchaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wpintro = T.nullable(T.string({ max=512 })),
})

-- WatchAction (action='watch', method=form_fields) -- includes/Actions/WatchAction.php
local action_watchaction_form = T.object({
  title = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpFormIdentifier = T.nullable(T.string({ max=512 })),
  wplabels = T.nullable(T.string({ max=512 })),
})

return {
  index_post_form = index_post_form,
  action_forms = {
    action_deleteaction_form,
    action_markpatrolledaction_form,
    action_mcrrestoreaction_form,
    action_mcrundoaction_form,
    action_protectaction_form,
    action_purgeaction_form,
    action_revertaction_form,
    action_rollbackaction_form,
    action_unprotectaction_form,
    action_unwatchaction_form,
    action_watchaction_form,
  },
}
