-- ---------------------------------------------------------------------------
-- index.php POST form schema - the standard wikitext edit-submission form
-- (EditPage.php). Generated from editpage-fields.json (extract_mediawiki_api.py,
-- heuristic $request->getXxx() scan - candidate field NAMES only, no type info,
-- so most fields are generously-capped nullable strings; a handful of known
-- checkbox/enum fields get a tighter FIELD_OVERRIDES entry in gen_editpage_form.py.
-- None are marked required since MediaWiki's own form-building logic determines
-- which fields are present per action (preview/save/diff).
-- ---------------------------------------------------------------------------
local index_post_form = T.object({
  bot = T.nullable(T.string({ max=8 })),
  editRevId = T.nullable(T.string({ max=512 })),
  editintro = T.nullable(T.string({ max=512 })),
  format = T.nullable(T.string({ max=512 })),
  minor = T.nullable(T.string({ max=8 })),
  mode = T.nullable(T.string({ max=512 })),
  model = T.nullable(T.string({ max=512 })),
  nosummary = T.nullable(T.string({ max=8 })),
  oldid = T.nullable(T.string({ max=512 })),
  parentRevId = T.nullable(T.string({ max=512 })),
  preload = T.nullable(T.string({ max=512 })),
  preloadparams = T.nullable(T.string({ max=2048 })),
  preloadtitle = T.nullable(T.string({ max=512 })),
  preview = T.nullable(T.string({ max=8 })),
  redlink = T.nullable(T.string({ max=8 })),
  section = T.nullable(T.string({ max=512 })),
  summary = T.nullable(T.string({ max=2048 })),
  undo = T.nullable(T.string({ max=512 })),
  undoafter = T.nullable(T.string({ max=512 })),
  watchthis = T.nullable(T.string({ max=8 })),
  wpAllowedProblematicRedirectTarget = T.nullable(T.string({ max=8 })),
  wpAntispam = T.nullable(T.string({ max=64 })),
  wpAutoSummary = T.nullable(T.string({ max=2048 })),
  wpChangeTags = T.nullable(T.string({ max=2048 })),
  wpChangeTagsAfterPreview = T.nullable(T.string({ max=8 })),
  wpDiff = T.nullable(T.string({ max=512 })),
  wpEditToken = T.nullable(T.string({ max=512 })),
  wpEdittime = T.nullable(T.string({ max=512 })),
  wpExtraQueryRedirect = T.nullable(T.string({ max=512 })),
  wpIgnoreBlankArticle = T.nullable(T.string({ max=8 })),
  wpIgnoreBlankSummary = T.nullable(T.string({ max=8 })),
  wpIgnoreProblematicRedirects = T.nullable(T.string({ max=8 })),
  wpIgnoreRevisionDeleted = T.nullable(T.string({ max=8 })),
  wpMinoredit = T.nullable(T.string({ max=8 })),
  wpPreview = T.nullable(T.string({ max=8 })),
  wpRecreate = T.nullable(T.string({ max=8 })),
  wpSave = T.nullable(T.string({ max=512 })),
  wpScrolltop = T.nullable(T.string({ max=512 })),
  wpSection = T.nullable(T.string({ max=512 })),
  wpSectionTitle = T.nullable(T.string({ max=512 })),
  wpStarttime = T.nullable(T.string({ max=512 })),
  wpSummary = T.nullable(T.string({ max=2048 })),
  wpTextbox1 = T.nullable(T.string({ max=1048576 })),
  wpTextbox2 = T.nullable(T.string({ max=1048576 })),
  wpUltimateParam = T.nullable(T.string({ max=4, enum={ ['1']=true } })),
  wpUndidRevision = T.nullable(T.string({ max=512 })),
  wpUndoAfter = T.nullable(T.string({ max=512 })),
  wpUnicodeCheck = T.nullable(T.string({ max=64 })),
  wpWatchlistExpiry = T.nullable(T.string({ max=512 })),
  wpWatchlistLabels = T.nullable(T.string({ max=2048 })),
  wpWatchthis = T.nullable(T.string({ max=8 })),
})
