#!/usr/bin/env python3
"""
Integrates the Tier 6 write-capable Special: page routes/forms (generated by
gen_special_pages.py) into mediawiki.lua:
  1. inserts the `local X_form` / `local X_route` blocks right after
     index_post_form's closing `})`
  2. inserts `X_route,` entries into the routes table, right before the
     generic "index php get" catch-all (most-specific-first ordering)

Usage: python3 integrate_special_pages.py
"""
import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _find_repo_root(start):
    d = start
    while d != os.path.dirname(d):
        if os.path.isdir(os.path.join(d, "rootfs", "etc", "openresty", "waf")):
            return d
        d = os.path.dirname(d)
    raise RuntimeError("could not find repo root above " + start)


ROOT = _find_repo_root(SCRIPT_DIR)
LUA_PATH = os.path.join(ROOT, "rootfs/etc/openresty/waf/apps/mediawiki.lua")

PAGE_LABELS = [
    "upload", "block", "unblock", "movepage", "userrights", "import",
    "export", "undelete", "emailuser", "mergehistory", "blocklist",
    "changecontentmodel",
]


def main():
    gen_proc = subprocess.run(
        [sys.executable, os.path.join(SCRIPT_DIR, "gen_special_pages.py")],
        capture_output=True, text=True, check=True,
    )
    forms_block = gen_proc.stdout

    src = open(LUA_PATH, encoding="utf-8").read()

    # 1) Insert the form/route declarations right after index_post_form's closing "})".
    marker = "})\n\n-- ---------------------------------------------------------------------------\n-- load.php GET query schema"
    if marker not in src:
        print("ERROR: could not find index_post_form end marker", file=sys.stderr)
        sys.exit(1)
    src = src.replace(marker, "})\n\n" + forms_block + "-- ---------------------------------------------------------------------------\n-- load.php GET query schema", 1)

    # 2) Insert "X_route," entries right before the generic "index php get" catch-all.
    route_entries = "".join(f"    {label}_route,\n" for label in PAGE_LABELS)
    catch_all_marker = '    {\n      name    = "index php get",'
    if catch_all_marker not in src:
        print("ERROR: could not find 'index php get' catch-all route marker", file=sys.stderr)
        sys.exit(1)
    src = src.replace(catch_all_marker, route_entries + catch_all_marker, 1)

    open(LUA_PATH, "w", encoding="utf-8").write(src)
    print(f"Integrated {len(PAGE_LABELS)} Special: page routes into {LUA_PATH}")


if __name__ == "__main__":
    main()
